### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by kevinvennitti** [divamgupta/diffusionbee-stable-diffusion-ui#18]
Hi!

I have an error when I start the app:

```
Uncaught Exception:
TypeError: Object has been destroyed
at IpcMainImpl.<anonymous> (/private/var/folders/qz/kbmfy__56z14l1xg6hzdzksr0000gn/T/AppTranslocation/93B9BEA5-64F3-4A8E-9A7E-EBD19AC93C47/d/DiffusionBee.app/Contents/Resources/app.asar/background.js:2:240352)
at IpcMainImpl.emit (events.js:315:20)
at Object.<anonymous> (electron/js2c/browser_init.js:161:10307)
at Object.emit (events.js:315:20)
at ChildProcess.<anonymous> (/private/var/folders/qz/kbmfy__56z14l1xg6hzdzksr0000gn/T/AppTranslocation/93B9BEA5-64F3-4A8E-9A7E-EBD19AC93C47/d/DiffusionBee.app/Contents/Resources/app.asar/background.js:2:244979)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1048:16)
at Socket.<anonymous> (internal/child_process.js:439:11)
at Socket.emit (events.js:315:20)
at Pipe.<anonymous> (net.js:673:12)
```

Timeline:

<img width="882" alt="screencapture-2022-09-12-16 54 31@2x" src="https://user-images.githubusercontent.com/9624530/189686856-f2c5a3ca-d8b2-4803-826c-c95a8ed5f252.png">

<img width="416" alt="screencapture-2022-09-12-16 54 33@2x" src="https://user-images.githubusercontent.com/9624530/189686818-af9de7d5-e673-4ee3-948a-30e89af65333.png">

<img width="416" alt="screencapture-2022-09-12-16 54 26@2x" src="https://user-images.githubusercontent.com/9624530/189686808-ee5ff277-e5d7-4af5-bc3c-104357f35812.png">

**macOS:**
![screencapture-2022-09-12-16 54 50@2x](https://user-images.githubusercontent.com/9624530/189686673-ef2ae963-c9b4-4064-b11d-0c9f7c28e2f5.png)

Feel free to ask any question to debug!

**Comment by discodan** [comment]
This is happening to me as well. 
![image](https://user-images.githubusercontent.com/5684423/189709822-c26aabd6-13cb-4423-af38-4abef914e1e4.png)

**Comment by banagale** [comment]
This also happened for me, but it started up fine on the second attempt.

**Comment by kevinvennitti** [comment]
I just reboot my Mac and it seems to work fine now! ✅ 
@discodan Would you try?

**Comment by divamgupta** [comment]
Could you open terminal and run it via there. 

```
cd <path_of_the_app>/DiffusionBee.app/Contents/MacOS
 ./DiffusionBee 
```

And paste the logs

**Comment by kapje** [comment]
Same problem as OP, log from CLI:


# ./DiffusionBee 
34.017968128 Is the free memory
68.719476736 Is the total memory
21.6.0 ohoho
native functions imported
starting briddddd
BrowserWindow {
  setBounds: [Function (anonymous)],
  _events: [Object: null prototype] {
    blur: [Function (anonymous)],
    focus: [Function (anonymous)],
    show: [Function: visibilityChanged],
    hide: [Function: visibilityChanged],
    minimize: [Function: visibilityChanged],
    maximize: [Function: visibilityChanged],
    restore: [Function: visibilityChanged],
    resize: [Function: R],
    move: [Function: R],
    close: [Function (anonymous)]
  },
  _eventsCount: 10,
  devToolsWebContents: [Getter]
}
browser object binded
browser object binded
Python response:  non threaded input for unix systems!
locale set failed
locale set failed 2

Python response:  utds loading_msg___U_P_D_A_T_E___" Loading model "
utds loading_percentage___U_P_D_A_T_E___-1

Python response:  utds loading_msg___U_P_D_A_T_E___"Downloading Model 1/2"

Python response:  utds loading_msg___U_P_D_A_T_E___"Checking Model"
utds loading_desc___U_P_D_A_T_E___""

stderr: Traceback (most recent call last):
  File "txt2img.py", line 340, in <module>

stderr:   File "txt2img.py", line 233, in main
  File "ldm/downloader.py", line 124, in download
AssertionError: The checksum for downloaded file failed.
[3379] Failed to execute script 'txt2img' due to unhandled exception!

**Comment by minrk** [comment]
It could do a better job reporting download errors, but I tracked it down to https://github.com/psf/requests/issues/2773 and the fact that I had an old Google API token for `www.googleapis` in my `~/.netrc` that looked like:

```
machine www.googleapis.com
  password 4/....
```

Removing those lines from my `~/.netrc` and trashing `~/.diffusionbee/downloads` fixed it (trashing downloads may not have been required).

Ignoring netrc is [weirdly complicated]( https://github.com/psf/requests/issues/2773) for requests if you don't want to _also_ ignore any http proxy configuration from the env.

Problems to fix:

- ignore netrc (requests `session.trust_env = False` or [NullAuth](https://github.com/psf/requests/issues/2773#issuecomment-174312831))
- When checksum fails, show the file and URL that failed
- Show download errors for checksum failures and/or initial request errors to user instead of opaque "Backend quit unexpectedly"

How I tracked it down:

```
$ ls ~/.diffusionbee/downloads
sd-v1-4.ckpt
$ head ~/.diffusionbee/downloads/sd-v1-4.ckpt
HTTP Basic Authentication is not supported for this API
```

which told me Basic Auth credentials were being sent that shouldn't be. Checked the URL including redirects by attempting the download myself:

```python
In [1]: import requests

In [2]: r = requests.get("https://me.cmdr2.org/stable-diffusion-ui/sd-v1-4.ckpt")

In [3]: r
Out[3]:
401 https://www.googleapis.com/storage/v1/b/aai-blog-files/o/sd-v1-4.ckpt?alt=media
headers:   Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
  Cache-Control: private, max-age=0
  Content-Length: 55
  Content-Type: text/html; charset=UTF-8
  Date: Tue, 13 Sep 2022 09:08:27 GMT
  Expires: Tue, 13 Sep 2022 09:08:27 GMT
  Server: UploadServer
  Vary: Origin, X-Origin
  WWW-Authenticate: basic realm="Google APIs"
  X-GUploader-UploadID: ADPycduebuCuAqg9MobtRu7fXDL0vOEa8L0P784ufrxRcdhkQzn_TJa6p_x5_QPERPRwCiNogkenaTwE-1xox0I0jmAQiauXwH1d

body (text/html; charset=UTF-8):
HTTP Basic Authentication is not supported for this API
```

found `machine www.googleapis.com` in my `~/.netrc`

**Comment by kapje** [comment]
An old .netrc that I didn't even know was there was indeed the problem - thanks minrk
