### ISSUE TITLE
Can't add any custom models: convert_model.py error

### ISSUE THREAD

**Issue by Bangkokian** [divamgupta/diffusionbee-stable-diffusion-ui#372]
I can't add any ckpt models due to the following error (M1 MacBook Pro)

```
Error Traceback (most recent call last):
File "convert_model.py", line 28, in <module>
KeyError: 'state_dict'
[26564] Failed to execute script 'convert_model' due to unhandled exception!
```

This appears to be the case with all ckpt models I've tried, so I don't believe the issue is with the models.

**Comment by hungryjos** [comment]
Experiencing same kind of error message (M1 Max Mac Studio):
`Error Traceback (most recent call last):
File "convert_model.py", line 47, in <module>
AssertionError
[52609] Failed to execute script 'convert_model' due to unhandled exception!`

**Comment by jwooldridge234** [comment]
Don't know when this is going to get fixed in the app, but I figured out a workaround. HOWEVER, I think this error happens because these file fail the unpickling safety check... so be extra sure the model doesn't contain any malicious code before you run this process.

1. Pull down this repo
2. Create a conda env by navigating to backends/stable_diffusion_tf and running "conda env create -f environment_m1.yml" (I'm assuming you're on macos)
3. Activate the env with "conda activate bee_env"
4. Navigate to the backends/model_converter folder
5. Run "pip install fickling" (requirement for the converter script)
6. Run the script with 'model_converter % python convert_model.py "<PATH TO MODEL>" "<PATH_WHERE_YOU_WANT_TO_SAVE_THE_OUTPUT>"'
7. This outputs a .tdict file. Drag this into ".diffusionbee/custom_models/"
8. Finally, edit ".diffusionbee/data.json" and add the new model at the bottom of the file in the "custom_models" section, like this: {"nameofmodel":{"name":"nameofmodel","path":"<PATH_TO_TDICT_FILE>","orig_path":"<PATH_TO_ORIGINAL_MODEL>"}

At that point, you should be able to start the app, and if you did it correctly, the model will be under the list of custom models and you can just use it.

Hope that helps! Feel free to ping me if you have any issues. Love this app, not as many features as Auto but runs so much faster on Mac

**Comment by zwzheng45** [comment]
@jwooldridge234 Hello, I followed your steps which did get a .tdict file and I think diffusion bee do recognize it. But when I tried to generate pictrues, it gives me this `Backend quit unexpectedly. ` error. I tried to convert several different models but they all gave me the same error. 

The `convert_model.py` also gave me an error after outputted the .tdict file. I don't know if there is anything do to with it.

`Traceback (most recent call last):
  File "/Users/zzw/Downloads/diffusionbee-stable-diffusion-ui-master/backends/model_converter/convert_model.py", line 99, in <module>
    assert k in keys_info , k
AssertionError: cond_stage_model.transformer.text_model.embeddings.position_ids`

**Comment by jwooldridge234** [comment]
Yeah I've seen that with a couple of models since I posted this. I was able to convert Dreamlike Diffusion 1.0, ShadyArt, and the Protogen mixes using this method, but others have failed with the same error. Not familiar enough with transformers to really debug what that error means, but I assume something to do with the model itself. Maybe somebody else will be able to weigh in and debug further. Sorry!

**Comment by SteveAtKlover** [comment]
Yeah, I get this error too...

"Error Traceback (most recent call last):
File "convert_model.py", line 28, in <module>
KeyError: 'state_dict'
[15210] Failed to execute script 'convert_model' due to unhandled exception!"

**Comment by zwzheng45** [comment]
The new converter is better than the one in 1.5.1 release for some model but it still doesn't convert everything. 

This is the answer I got in discord chat about this error:

> typically this error means the model is doing things that Diffusion Bee isn't expecting
it has a list of keys it is expecting and if there is a key that DBee isn't built to deal with the importer bails

**Comment by dogma4000** [comment]
> 

Alright so... I have no idea what you just said. I have same issue as the others here, but I don't know anything about how to implement the steps you mentioned. I'm assuming the commands you provided need to be entered into terminal (I'm on mac). Could I ask you to re-explain like I'm five? lol

**Comment by jwooldridge234** [comment]
> Alright so... I have no idea what you just said. I have same issue as the others here, but I don't know anything about how to implement the steps you mentioned. I'm assuming the commands you provided need to be entered into terminal (I'm on mac). Could I ask you to re-explain like I'm five? lol

I'm not always the best at explaining stuff, but I'll give it a try. First, pin the terminal app in the bottom bar if it isn't already- you're going to want easy access to it.

You're going to want to install Conda. Grab this file (https://www.anaconda.com/products/distribution) and install it as you would any other application. When it's done, open a terminal and type "conda list" which should print a list of packages. If it doesn't, conda didn't install directly.

(Conda is an environment manager for python. Super important if you want to run different python apps that have different version requirements on the same computer.)

Now that you've installed Conda, open a terminal in the directory where you want to install the DiffusionBee repo (you can drag/drop from the Finder to the terminal app in the bottom bar). At this point, you should be able to follow my original steps. Lmk if you have any questions!

**Comment by dogma4000** [comment]
I DL'd conda and ran the conda list like you said. Pretty much lost from there. I don't really understand your steps from above, to be honest. I'm extremely new to all this and don't understand a thing about scripts and commands. It's okay though. Thanks for your help anyways!

**Comment by iKora128** [comment]
Thanks [jwooldridge234] !! I finally convert my model..
My procedure is under this.

1. Pull down this repo(download or git pull) 
2. Change directory to  `cd your_pull_directory/backends/stable_diffusion_tf`
3. Create conda env `conda create -n bee_env python=3.8 -y`
4. Activate the env with `conda activate bee_env`
5. Then download requirements `pip install -r requirements.txt`
6. Chance directory to the backends/model_converter `cd your_pull_directory/backends/model_converter`
7. Run `pip install fickling`
8. Run the script with: `python convert_model.py "/path_your_mode" "/path_you_want_to.tdict" `
9. This outputs a .tdict file. Drag this into ".diffusionbee/custom_models/"
10. Finally, edit ".diffusionbee/data.json" and add the new model at the bottom of the file in the "custom_models" section, like this: "nameofmodel":{"name":"nameofmodel","path":"PATH_TO_TDICT_FILE","orig_path":"PATH_TO_ORIGINAL_MODEL"}

**Comment by rishabhrana3006** [comment]
Clearer instructions for dummies like me in the future. Here we are basically cloning(copying) the source code files from the github repo so that we can run some part of it on our terminal to convert .ckpt model files to .tdict model files which are used the diffusionbee software that you are currently using.

But first we need to install miniconda on our zsh terminal:
1. Open terminal
2. Enter command `curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/miniconda.sh
`
3. Enter command `zsh ~/miniconda.sh -b -p` if your terminal shell is zsh or enter `bash ~/miniconda.sh -b -p` if your terminal shell is bash
4. Now we need to add the installed file to the GLOBAL PATH, for that basically do ( I am only telling instructions for zsh terminal here)
5. `sudo nano ~/.zshrc` to open the zshrc file in nano editor
6. scroll down to the button of the opened file and enter `export PATH="$HOME/miniconda3/bin:$PATH"`
7. Now press `control + x`, press `Y`, press `enter` to save the zshrc file changes
8. Now enter command `source ~/.zshrc` This instructs terminal to reread the zshrc file
[https://developers.google.com/earth-engine/guides/python_install-conda#mac](Link of original installation guide)

Now that we are done with conda. You need to have git installed so that you can clone the repo, just watch youtube tutorial for how to install and setup git and clone repos, or you can directly download the file contents from the repo page.

The next step involves getting the exact path of your cloned directory. Basically open finder application and go to the cloned/downloaded folder, right click on it, now press `option` key, and click on `copy "your_file" as Pathname`.
This copied file path text is the `path__to__your__directory`. Replace it in the below instructions

1. After opening terminal, change directory to `cd path__to__your__directory/backends/stable_diffusion_tf`
2. Enter in command `conda env conda create -n bee_env python=3.8 -y`
3. Activate the env with command `conda activate bee_env`
4. Then download requirements by entering the command `pip install -r requirements.txt`
5. Chance directory to the backends/model_converter by entering `cd path__to__your__directory/backends/model_converter`
6. Run `pip install numpy` for insurance
7. Run `pip install fickling`
8. Now get the path of your model.ckpt file using the same method you got your directory path
9. Run the script with: `python convert_model.py "/path_your_model/model.ckpt" "/path_you_want_to_save the converted_file/file_name.tdict" `
10. This outputs a .tdict file which we can use
11. Now open your main user directory in your finder app, press `command + shift + .` to show all the hidden folders
12. Here there is .diffusionbee folder which has contents used by the diffusion bee software when you run it
13. Drag converted model.tdict into ".diffusionbee/custom_models/"
14. Finally, edit ".diffusionbee/data.json" using any text editor and add the new model at the bottom of the file in the "custom_models" section, like this: "nameofmodel":{"name":"nameofmodel","path":"PATH_TO_TDICT_FILE","orig_path":"PATH_TO_ORIGINAL_MODEL"}

**Comment by JieLinYang5487** [comment]
Hi, I try to do the same instruction but I ca not understand the last part, is add the tex like this? 
"custom_models":{“nameofmodel”:{"name":"nameofmodel","path":"PATH_TO_TDICT_FILE","orig_path":"PATH_TO_ORIGINAL_MODEL"}}
And, what should "orig_path"  put with? Is still the path of TDICT?

**Comment by zwzheng45** [comment]
Yes, you got the correct format.
For the original path, I think it only affects what will be displayed in the software settings to help you find the original model. Diffusionbee is only using the tdict model so it doesn't matter what you put in for ```orig_path```.

**Comment by nightwatcher26** [comment]
Thanks for this solution, everyone. It worked for the DreamShaper model with DiffusionBee. 
I did notice that DiffusionBee rejected the revised data.json file when I had the incorrect orig_path for the model, so the path to the ckpt file does appear to matter.
One other note: For some reason `conda activate bee_env` didn't work, but `source activate bee_env` worked instead.
