### ISSUE TITLE
Stable diffusion model failed to load,

### ISSUE THREAD

**Issue by badralyassini** [divamgupta/diffusionbee-stable-diffusion-ui#373]
Hello, please I need your help, I tried to install 3 versions of stable diffusion 1.4, 1.5, and 2.0 and yet I have the same error message ( Stable diffusion model failed to load, exiting ). Thank you in advance for your help.

loading stable diffusion model: AttributeError
Traceback (most recent call last):
  File "D:\SDlocal\webui.py", line 74, in initialize
    modules.sd_models.load_model()
  File "D:\SDlocal\modules\sd_models.py", line 322, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "D:\SDlocal\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\SDlocal\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "D:\SDlocal\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "D:\SDlocal\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\SDlocal\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 100, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "D:\SDlocal\venv\lib\site-packages\transformers\modeling_utils.py", line 2006, in from_pretrained
    loaded_state_dict_keys = [k for k in state_dict.keys()]
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by saulcastac** [comment]
Where you able to solve it ?

**Comment by mattymatty** [comment]
same error
