### ISSUE TITLE
Error Traceback (most recent call last): File "convert_model.py", line 47, in <module> AssertionError [16904] Failed to execute script 'convert_model' due to unhandled exception!

### ISSUE THREAD

**Issue by terion-name** [divamgupta/diffusionbee-stable-diffusion-ui#386]
Loading model: https://civitai.com/models/2540/elldreths-stolendreams-mix (and many others)

Getting:
<img width="321" alt="Снимок экрана 2023-02-06 в 00 54 09" src="https://user-images.githubusercontent.com/1060205/216850683-9acefad0-1fec-4ff4-b60f-5885ca9e171e.png">

Error Traceback (most recent call last):
File "convert_model.py", line 47, in <module>
AssertionError
[16904] Failed to execute script 'convert_model' due to unhandled exception!

**Comment by jimbo1111** [comment]
I get the same with any ckpt I try to load

**Comment by KingMob** [comment]
Likewise.

**Comment by arthurborgesdev** [comment]
Same thing.

**Comment by Promisey** [comment]
Same thing here. Have anyone solved it?

**Comment by codyranney** [comment]
still no fix i get the same

**Comment by dbashkatoff** [comment]
> My own 1.5 trained model works, but not my own trained 2.1 Models.
diffusionbee works with the base model SD 1.5
