### ISSUE TITLE
Issue of converting models from .ckpt to .tdict: 'Exception: storage type not defined!'

### ISSUE THREAD

**Issue by yscity2006** [divamgupta/diffusionbee-stable-diffusion-ui#401]
Recently, I attempted to upload a custom model 'MeinaMix' and somehow this error appeared. Does anyone know how to fix this?
`Error Traceback (most recent call last):`
`File "convert_model.py", line 53, in <module>`
`File "fake_torch.py", line 104, in extract_weights_from_checkpoint`
`File "fake_torch.py", line 153, in examine_pickle`
`File "fake_torch.py", line 265, in __init__`
`File "fake_torch.py", line 304, in parse_instruction`
`File "fake_torch.py", line 354, in _torch_to_numpy`
`Exception: Storage type not defined!`
`[4001] Failed to execute script 'convert_model' due to unhandled exception!`
<img width="521" alt="Screenshot 2023-03-03 at 12 05 51" src="https://user-images.githubusercontent.com/120778608/222637171-3af3deab-a35a-46db-9278-953f622295c4.png">

**Comment by divamgupta** [comment]
Could you post a link to the model?

**Comment by yscity2006** [comment]
The link to the model:
MeinaMix, tried to download v8 but failed
https://huggingface.co/Meina/MeinaMix

**Comment by SouthbayJay** [comment]
I'm getting the same errors trying to install DreamShaper V5

**Comment by SouthbayJay** [comment]
> The link to the model: MeinaMix, tried to download v8 but failed https://huggingface.co/Meina/MeinaMix

Did you find a fix for the error?

**Comment by yscity2006** [comment]
Nope, looks like I have to use stable diffusion webUI for this model...
