### ISSUE TITLE
Unable to install new model .ckpt 

### ISSUE THREAD

**Issue by photodarren** [divamgupta/diffusionbee-stable-diffusion-ui#412]
When I try to install any .ckpt model I get an error that tells me it is trying to unpack a zip.
I tried zipping a model for it to unzip, but the file selection only allows .ckpt files.

This is the error of an example file. 

Error Traceback (most recent call last):
File "convert_model.py", line 53, in <module>
File "fake_torch.py", line 104, in extract_weights_from_checkpoint
File "zipfile.py", line 1257, in __init__
File "zipfile.py", line 1324, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
[78474] Failed to execute script 'convert_model' due to unhandled exception!

**Comment by divamgupta** [comment]
Which model are you trying to import?

**Comment by yvanda** [comment]
yeah, i got the same issue.
