### ISSUE TITLE
App opens with white Screen (caused by PyTorch?)

### ISSUE THREAD

**Issue by iXizz3l** [divamgupta/diffusionbee-stable-diffusion-ui#42]
Hi, never did this here before so tell me if something is missing.
I am running on a MacBook with M1 with a fresh installed updated MacOS.
When I open the App I get only a white Box. I followed a tip in an other Issue and started the app from the terminal app.
I got the following error:

`
browser object binded
browser object binded
Python response:  non threaded input for unix systems!
locale set failed
locale set failed 2
 
Python response:  utds loading_msg___U_P_D_A_T_E___" Loading model "
utds loading_percentage___U_P_D_A_T_E___-1
 
stateeee
{ x: 751, y: 75, width: 770, height: 550, isMaximized: false }
Python response:  utds loading_msg___U_P_D_A_T_E___" Loading model "
utds loading_percentage___U_P_D_A_T_E___-1
 
Python response:  utds loading_desc___U_P_D_A_T_E___""
 
Python response:  utds loading_msg___U_P_D_A_T_E___" Loading model "
utds loading_percentage___U_P_D_A_T_E___-1
 
Python response:  Loading model from /Users/macos/.diffusionbee/downloads/sd-v1-4.ckpt
 
Python response:  Global Step: 470000
 
Python response:  LatentDiffusion: Running in eps-prediction mode
 
Python response:  DiffusionWrapper has 859.52 M params.
 
Python response:  making attention of type 'vanilla' with 512 in_channels
 
Python response:  Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
 
Python response:  making attention of type 'vanilla' with 512 in_channels
 
stderr: Traceback (most recent call last):
  File "txt2img.py", line 340, in <module>
 
stderr:   File "txt2img.py", line 293, in main
  File "txt2img.py", line 122, in load_model_from_config
  File "pytorch_lightning/core/mixins/device_dtype_mixin.py", line 109, in to
  File "torch/nn/modules/module.py", line 987, in to
  File "torch/nn/modules/module.py", line 639, in _apply
  File "torch/nn/modules/module.py", line 639, in _apply
  File "torch/nn/modules/module.py", line 639, in _apply
  [Previous line repeated 1 more time]
  File "torch/nn/modules/module.py", line 662, in _apply
  File "torch/nn/modules/module.py", line 985, in convert
RuntimeError: block_found && buffer_block INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1662188943573/work/aten/src/ATen/mps/MPSAllocator.mm":124, please report a bug to PyTorch. 
[559] Failed to execute script 'txt2img' due to unhandled exception!`

**Comment by muuuh** [comment]
same here (but in utm 12.5.1 macos vm with 12GB ram allocated), seems similar to https://github.com/lstein/stable-diffusion/issues/244
