### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by Return-1** [divamgupta/diffusionbee-stable-diffusion-ui#429]
**The crash logs**
<img width="439" alt="Screenshot 2023-05-16 at 3 13 16 PM" src="https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/11403706/525bc535-56f1-45b7-8125-8d1183cafe6d">

**My environment info**
<img width="569" alt="Screenshot 2023-05-16 at 3 13 01 PM" src="https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/11403706/aa22145d-82a3-4218-a751-81ab0418087e">

I've tried restarting/redownloading, changing my internet connection, check for firewalls but nothing seems to be working.
Any steps i can take to narrow the problem down ( like look at logs if any are generated or something? )

_I've avoided upgrading because i heard there's issues with Ventura_

**Comment by Return-1** [comment]
Some info i got my hands on while running on DEBUG=1 mode

```
stderr: Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__

stderr:   File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/Volumes/DiffusionBee 1.7.4-arm64 1/DiffusionBee.app/Contents/Resources/core/./ncc_sd.dylib, 0x0006): Symbol not found: _OBJC_CLASS_$_MPSGraphRandomOpDescriptor
  Referenced from: /Volumes/DiffusionBee 1.7.4-arm64 1/DiffusionBee.app/Contents/Resources/core/ncc_sd.dylib
  Expected in: /System/Library/Frameworks/MetalPerformanceShadersGraph.framework/Versions/A/MetalPerformanceShadersGraph

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "diffusionbee_backend.py", line 42, in <module>
  File "build/interface.py", line 10, in init interface
  File "build/int_1.py", line 53, in init int_1
  File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll '/Volumes/DiffusionBee 1.7.4-arm64 1/DiffusionBee.app/Contents/Resources/core/./ncc_sd.dylib'. Most likely this dynlib/dll was not found when the application was frozen.
[46694] Failed to execute script 'diffusionbee_backend' due to unhandled exception!

Python response:  starting backend
non threaded input for unix systems!
not adding sys paths
Unified Interface
TODO : build the dll for prod! not debug
```
