### ISSUE TITLE
Asking for Help: Failure in Importing Custom Models

### ISSUE THREAD

**Issue by AstralGoGod** [divamgupta/diffusionbee-stable-diffusion-ui#430]
Error Traceback (most recent call last):
File "diffusionbee_backend.py", line 325, in <module>
File "convert_model.py", line 67, in convert_model
File "safetensor_wrapper.py", line 24, in __getitem__
File "numpy/__init__.py", line 320, in __getattr__
AttributeError: module 'numpy' has no attribute 'bfloat16'
[61136] Failed to execute script 'diffusionbee_backend' due to unhandled exception!

**Comment by camilovietnam** [comment]
No idea, but how about checking your python version? If you have python2, how about running python3? It works fine for me under Python 3.10.8

**Comment by etamity** [comment]
I am getting same error, how do you run python3 in diffusionbee?

**Comment by Brog33** [comment]
![image](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/1303537/af2f8be7-fe0b-45d7-b464-cca9153d9103)

version 2.2.1

**Comment by aakashgupt** [comment]
same issue
