### ISSUE TITLE
bee version 2.4.3 cannot import "juggernautXL_v7Rundiffusion.safetensors" model from civitai

### ISSUE THREAD

**Issue by h0nor** [divamgupta/diffusionbee-stable-diffusion-ui#488]
Cannot import the model I downloaded from civitai, "juggernautXL_v7Rundiffusion.safetensors"
I am using bee version 2.4.3

Error while importing Traceback (most recent call last): File "diffusionbee_backend.py", line 212, in File "convert_model.py", line 97, in convert _model ValueError: The model is not supported. Please make sure it is a valid SD 1.4/1.5/2.1 .ckpt/safetensor file [345581 Failed to execute script 'diffusionbee_backend' due to unhandled exception

<img width="1724" alt="Screen Shot 2023-12-24 at 21 53 36" src="https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/30260964/2ded7f62-a66b-4dcd-840e-325433d6a98f">

**Comment by l0stl0rd** [comment]
I have that issue with all the custom SDXL models I tried.

**Comment by sfxphil** [comment]
Having exact same issue with that model

**Comment by thisplantguy** [comment]
Same here as well. The SDXL base model works but no custom models even let me load them into the app. Seems like the 2.4.3 version supporting SDXL wasn't implemented properly.

**Comment by mikestreed** [comment]
The built-in SDXL base model downloads a TDICT file directly, instead of the safetensors file you get from Civit. Seems SDXL will work fine with a TDICT file but the function to convert safetensors to TDICT on import doesnt work (yet). I assume and hope this will be the next major thing to fix, as well as proper Lora support. By far the 2 most important missing features at the moment, imo.

**Comment by divamgupta** [comment]
More SDXL models added !

You can import tdicts in Bee

**Comment by mikestreed** [comment]
Thanks for Juggernaught and RealVis! Would be nice to be able to use any XL model we want eventually (especially the XL Turbo models),.. is there a way we can manually convert to TDICT elsewhere to import? Or is TDICT proprietary to you? (I cant find any other info on it). 

Also a question: why are the TDICT files like 4.5GB for an XL model where the safetensors file is 6-8GB.

Thanks!
