### ISSUE TITLE
ValueError: The model is not supported.

### ISSUE THREAD

**Issue by InvisibleTroll** [divamgupta/diffusionbee-stable-diffusion-ui#510]
MacBook Pro 14in 2021 
Apple M1 Pro 
MacOS 14.3 (Sonoma)
DiffusionBee_MPS_arm64-1.7.4.dmg

Got error when trying to import [sd_xl_base_1.0.safetensors] from https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/tree/main :

Error convert_model.py:48: RuntimeWarning: divide by zero encountered in divide
Traceback (most recent call last):
File "diffusionbee_backend.py", line 325, in <module>
File "convert_model.py", line 80, in convert_model
ValueError: The model is not supported. Please make sure it is a valid SD 1.4/1.5/2.1 .ckpt/safetensor file
[4686] Failed to execute script 'diffusionbee_backend' due to unhandled exception!

**Comment by zhstark** [comment]
Looks like it doesn't support SD XL models
