### ISSUE TITLE
Issue importing model, does nothing (SDXL?)

### ISSUE THREAD

**Issue by haakonnessjoen** [divamgupta/diffusionbee-stable-diffusion-ui#520]
I tried to import ZavyChromaXL from https://civitai.com/models/119229/zavychromaxl.

Testing with Diffusion Bee Version 2.5.1 (0038)

Diffusion bee reads the file for a while, and it has loading animation in the UI. But then suddenly it just pretends to have finished. But nothing has changed. It doesn't add it. And nothing is added to the logfile.

I tried running the convert_model.py tool from this repository manually, and the following happened:

```
-----snip----- (pages of data) -----snip----

, 'ones_3840', 'zeros_1536', 'ones_1536', 'zeros_4160', 'ones_4160', 'zeros_1664', 'ones_1664', 'zeros_4480', 'ones_4480', 'zeros_1792', 'ones_1792', 'zeros_4800', 'ones_4800', 'zeros_5120', 'ones_5120', 'zeros_2048', 'ones_2048', 'zeros_5440', 'ones_5440', 'zeros_2176', 'ones_2176', 'zeros_5760', 'ones_5760', 'zeros_2304', 'ones_2304', 'zeros_6080', 'ones_6080', 'zeros_2432', 'ones_2432', 'zeros_6400', 'ones_6400']
shape mismatch model.diffusion_model.input_blocks.0.0.weight (320, 9, 3, 3) (320, 4, 3, 3)
Traceback (most recent call last):
  File "/Users/haakon/src/diffusionbee-stable-diffusion-ui/backends/model_converter/./convert_model.py", line 156, in <module>
    convert_model(checkpoint_filename , out_filename )
  File "/Users/haakon/src/diffusionbee-stable-diffusion-ui/backends/model_converter/./convert_model.py", line 86, in convert_model
    raise ValueError("The model is not supported. Please make sure it is a valid SD 1.4/1.5/2.1 .ckpt/safetensor file")
ValueError: The model is not supported. Please make sure it is a valid SD 1.4/1.5/2.1 .ckpt/safetensor file
```

Does this mean that Diffusion Bee only supports SD 1.5 and not SDXL 1.5?
I think most models on civitai are SDXL 1.5, so that's why they won't import? Maybe Diffusion Bee should give a message about this, when you fail to load a model. So it's easier for people to understand.

Anyways, even if you're not adding support for SDXL, it would be nice to at least get a warning message when the model doesn't import. So I will post this issue, even if I probably figured out the reason for the model not importing.

**Comment by Liane0827** [comment]
I holp can support SDXL

**Comment by SmartDigitalNetworks** [comment]
I saw you were recently working on an update. I recently found this info and thought I'd pass it along, Not sure if this will help but looks likes there was an error in the safetenors to diffuser. Not sure if this is related but my intuition tells me it might be.

Converting .safetensor model to diffusers
https://github.com/huggingface/diffusers/issues/4974
You just have to change the line 155 to checkpoint_path_or_dict in the convert_original_stable_diffusion_to_diffusers.py file
