### ISSUE TITLE
Nondescript error popup when trying to train Stable Diffusion XL

### ISSUE THREAD

**Issue by Crazygird** [divamgupta/diffusionbee-stable-diffusion-ui#523]
<img width="1076" alt="Screenshot 2024-06-29 at 1 13 15 PM" src="https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/95974074/92157b56-fc66-4409-87a7-13d24f77f73a">

Resolution: 768x768
Iterations: 2000
Size: 16

Mac M2, 16G of RAM

**Comment by JV-conseil** [comment]
Empty `AssertionError` when reviewing logs with `Show Logs` 👇

```log
got b2py rapp lora_training {
    "dataset_path": "~/dataset",
    "selected_sd_model": "Stable Diffusion XL Base 1.0",
    "img_width": 1216,
    "img_height": 1216,
    "out_dir": "~/train_model/",
    "out_name": "T1 SD XL Base 1.0",
    "train_iters": 1500,
    "lora_rank": 8,
    "applet_name": "applet_lora_training",
    "model_tdict_path": "~/.diffusionbee/downloaded_assets/Stable Diffusion XL Base 1.0_sd_xl_base_1.0_f8.tdict",
    "available_text_emb_words": {},
    "num_steps": 25,
}

[SD] dataset : [
    (
        "~/dataset/1.jpg",
        "The image shows a person with short brown hair smiling at the camera. The individual is wearing a dark-colored top or sweater that appears to be made of a knit fabric. The background is plain and light-colored, providing no distractions from the subject. There are no discernible objects or text in the image.",
    ),
    (
        "~/dataset/2.jpg",
        "The image features a person with short brown hair, wearing a dark green top with lace detailing at the neckline. The individual is smiling directly at the camera, and their expression appears friendly and approachable. The background is plain and light-colored, providing no distractions from the subject. There are no discernible texts or additional objects in the image.",
    ),
    (
        "~/dataset/3.jpg",
        "The image shows a person with short brown hair smiling at the camera. The individual is wearing a dark green top with lace detailing around the neckline and shoulders. The background is plain and light-colored, providing no distractions from the subject.",
    ),
    ...
]

json pos 384 450131

Traceback (most recent call last):
File "diffusionbee_backend.py", line 225, in diffusion_bee_main
File "applets/applets.py", line 16, in run_applet
File "applets/lora_training.py", line 290, in run
File "stable_diffusion/utils/model_interface.py", line 65, in create_sd_model_with_weights
File "stable_diffusion/utils/model_interface.py", line 29, in load_weights_model
File "build/int_1.py", line 1020, in int_1.ModelInterface.load_from_tdict
File "build/int_1.py", line 162, in int_1.load_from_tdict
AssertionError
```
